neurostuff/PyMARE

- pymare/core.py
- pymare/estimators/__init__.py
- pymare/estimators/estimators.py
- tests/conftest.py
- tests/test_estimators.py
Adds a new `SampleSizeBasedLikelihoodEstimator` class that produces maximum-likelihood random-effects estimates for datasets that have estimates and sample sizes but no variances. This is maybe the modal situation with fMRI data, so it's a nice thing to have.
The approach is based on a simple idea in [this paper](https://www.ncbi.nlm.nih.gov/pubmed/28681700) (though I'm sure it's been suggested before in other places), which is to replace the standard log-likelihood function for the random-effects model with an analogous LL based not only beta and tau^2, but also a sigma^2 parameter that's scaled by the (known) inverse sample size. I.e., instead of study estimates being distributed with a variance of `tau^2 + v` (where `v` is the vector of observed sampling variances for the available …
> Add sample size-based ML/REML estimators

- pymare/estimators/estimators.py
Updated version of #18 with some extra patching: adds references and extends the `SampleSizeBasedLikelihoodEstimator` to handle additional covariates (i.e., meta-regression).
> Fixes to SampleSizeBasedLikelihoodEstimator

- pymare/estimators/estimators.py
- pymare/info.py
- pymare/results.py
- pymare/tests/conftest.py
- pymare/tests/test_estimators.py
- pymare/tests/test_results.py
Adds permutation testing: `pymare.results.permutation_test` accepts any `MetaRegressionResult` instance as input, and produces a `PermutationTestResult` instance. Currently all this is really good for is adding a permutation-based p-value, but the basic architecture seems reasonable, so we can expand on this later.
A nice feature is that the permutation testing capitalizes on the dataset vectorization introduced in #26, so, for closed-form estimators, this is really fast.
Closes #18: I initially planned to add bootstrapping-based CIs as well—and probably still will at some point—but I realized that it isn't possible to easily vectorize the bootstrap samples the same way as the permutations (the issue is that the `X` matrix is constant for permutations, but needs to be resampled for …
> Permutation testing

- .circleci/artifact_path
- .circleci/config.yml
- docs/requirements-dev.txt
- pymare/info.py
Closes None. Takes approach from pybids, fmriprep, and NiMARE.
Changes proposed in this pull request:
- Add step in CircleCI config for building docs.
- Add artifact_path file with path to doc main page.
- Also, fix the docs (hopefully).
> [TST, FIX] Add CI step for building docs

- docs/requirements-dev.txt
- pymare/info.py
RTD is still failing, currently because sphinx_gallery requires matplotlib.
> [FIX, DOC] Add matplotlib to RTD dependencies

- pymare/results.py
- pymare/stats.py
- pymare/tests/test_results.py
- pymare/tests/test_stats.py
Adds heterogeneity test and associated statistics to `MetaRegressionResults` via `get_heterogeneity_stats()`. Currently reports Q (i.e., weighted sum of squared residual error), I^2 (% of error due to heterogeneity), H (ratio of fixed-effects:random-effects SDs), and p-values for Q (by reference to a chi-square distribution with `k - p` DFs).
> ENH: Add heterogeneity test and associated stats

- setup.py
Closes #41.
Adds json files in `effectsize/` to setup `pkg_data` to bundle it with the released library.
> [FIX] Package json file with library

- pymare/estimators/__init__.py
- pymare/estimators/combination.py
- pymare/estimators/estimators.py
- pymare/results.py
- pymare/tests/test_combination_tests.py
- pymare/tests/test_estimators.py
- pymare/tests/test_results.py
Fixes/improves the combination test implementations (Stouffer's and Fisher's methods):
* Moves combination tests into their own module.
* Simplifies internal logic of base `CombinationTest` class.
* Fixes problems with returned p-values (#36).
* Adds concordant and directed test modes (see #39).
* Adds nicely parameterized tests.
This leaves some inconsistencies with the results returned by other estimators, and I have some ideas for improving/simplifying the handling of `Dataset` inputs, but I'll merge this first to keep things modular.
Closes #36.
Closes #39.
> Fix combination tests

- README.md
- examples/02_meta-analysis/plot_run_meta-analysis.py
- pymare/core.py
- pymare/estimators/combination.py
- pymare/estimators/estimators.py
- pymare/results.py
- pymare/tests/test_combination_tests.py
- pymare/tests/test_estimators.py
- pymare/tests/test_results.py
- pymare/tests/test_stan_estimators.py
Makes some API changes for improved `Dataset` handling and more sklearn-like behavior:
* The `fit()` method in estimator classes no longer takes `Dataset` instances; it now takes numpy arrays.
* The internal `_fit()` methods have been removed in favor of the public `fit()` methods.
* The old `fit()` behavior can now be reproduced by calling`fit_dataset()`.
* All `fit()` methods now return `self` instead of the fitted parameters (which are stored in `.params_`).
@tsalo I expect this will break NiMARE's IBMA classes; I can patch this myself if you like, but I expect it should be as simple as either renaming `fit_()` to `fit()` everywhere, or using `fit_dataset()` instead of `fit()`, depending on which pattern you're currently using. And I'm guessing you'll probably need to explicitly …
> [REF] Improved Dataset fitting

- pymare/estimators/estimators.py
- pymare/results.py
- pymare/stats.py
- pymare/tests/test_stats.py
To avoid optimization failures in `q_profile()` (see discussion in #40), we now pick a starting value for the upper CI of tau^2 based on the data (double the Dersimonian-Laird estimate of tau^2). This should hopefully work better than using a constant value. But, seeing as there will probably still be some non-zero rate of failure, we also now catch exceptions and set the CI values to `NaN`.
Closes #40.
> [FIX] minimization issues

- .codecov.yml
Lowers codecov coverage requirements so tests don't fail any time coverage goes down (unless the decrease >= 2%).
Closes #53
> [CI] Relax Codecov coverage requirements

- .zenodo.json
- README.md
- docs/index.rst
Closes #31.
- Add Zenodo badges to README and docs/index.rst.
- Add myself to the Zenodo file.
> Add Zenodo badges to documentation

- .github/workflows/testing.yml
Closes #76. Given the low activity in this repository, this new job should catch issues with new versions of dependencies.
> Run unit tests automatically every Sunday

- pymare/estimators/combination.py
- pymare/estimators/estimators.py
- pymare/results.py
- pymare/tests/test_effectsize_base.py
This should fix the currently failing linter CI step.
> Run updated version of black to fix CI

- pymare/effectsize/expressions.py
Closes #80.
- Replace `simply.core.compatibility.exec_` call with`exec`.
> Remove use of deprecated `sympy.core.compatibility` module

- pymare/core.py
- pymare/tests/test_core.py
- pymare/utils.py
Closes #88.
- Allow `n` with DataFrame-based Datasets.
- Make `X` optional for Datasets.
- Improve the associated test.
> Make n and X optional for DataFrame-based Datasets

- pymare/results.py
- pymare/tests/test_estimators.py
Closes #97.
- Make covariance matrix 3D in the right shape (`n_regressors`, `n_regressors`, `n_datasets`) instead of  (`n_regressors`, `n_datasets`, `n_regressors`).
- Test variable shapes in all Estimator tests.
> Fix maximum likelihood Estimators' SE outputs

- pymare/estimators/combination.py
- pymare/estimators/estimators.py
- pymare/results.py
- pymare/tests/test_results.py
Closes #52.
- Overwrite Estimators' `.dataset_` attribute with None when calling `fit()`. `fit_dataset()` will then replace that with the actual Dataset if it is called. Otherwise, `.dataset_` will remain None.
- This allows us to initialize Results objects, which assign an attribute (`.dataset`) from `Estimator.dataset_`.
- Check if `Result.dataset` is None _before_ using it. When it is None, raise a ValueError. 
- Add warnings to Result method docstring about whether `fit` is okay or if you need `fit_dataset`.
- This way, it is clear when `fit`-generated Results' methods can be used and when you need a `fit_dataset`-generated Result.
- Test the new behavior.
> Allow Results objects to work with Estimators' fit() method

- .zenodo.json
- pymare/core.py
- pymare/tests/test_utils.py
- pymare/utils.py
Closes #99.
Changes proposed in this pull request: 
- Add `_check_inputs_shape()` function to `utils.py` to avoid repetitive code.
- Add shape check to Dataset initialization: 
- Check whether the number of rows of `y` matches `X`.
- Check whether the number of rows and columns of `y` match `v`.
- Check whether the number of rows and columns of `y` match `n`.
**Note:** I didn't check for the number of columns of `X` vs the length of `X_names`, because an exception is raised in case of any mismatch when `_get_predictors()` is applied.
> Add shape check to Dataset initialization

- pymare/stats.py
Closes #109.
In the latest scipy release, the use of `minimize` with `x0.ndim != 1` is being deprecated. 
Currently, the output of `ub_start = 2 * DerSimonianLaird().fit(y, v, X).params_["tau2"]` is already a 1D array so the use of `minimize` with `[ub_start]` gives `x0.ndim = 2`, which then gets converted to an array of dimension 0 by `np.squeeze(x0)`, resulting in an error here:
https://github.com/scipy/scipy/blob/903bc39809af20a1447ed702e84592397c3de509/scipy/optimize/_minimize.py#L947
Changes proposed in this pull request:
- Remove square brackets from `ub_start` in `minimize`.
> Use 1D array in `scipy.optimize.minimize`

- .github/workflows/python-publish.yml
- .github/workflows/testing.yml
- pymare/__init__.py
- setup.cfg
Closes #113.
Changes proposed in this pull request:
- Add deprecation warnings when running NiMARE on Python 3.6 or 3.7.
> Raise deprecation warnings with Python 3.6 and 3.7

- .github/workflows/testing.yml
- docs/installation.rst
- setup.cfg
> Support Python 3.10

- .github/workflows/testing.yml
- pymare/estimators/combination.py
- pymare/tests/test_combination_tests.py
- pymare/tests/test_results.py
> Support precomputed correlation matrix for calculating variance inflation term in Stouffers

- pymare/estimators/combination.py
- pymare/tests/test_combination_tests.py
only positive z-values were displayed even if the p-value came from the "less than" array, this fixes that error.
> [FIX] concordant z values
